### ISSUE TITLE
Port .net core?

### ISSUE THREAD

**Issue by pimbrouwers** [dotarj/protobuf-net-data#34]
Any plans on porting this to .net core? I'm happy to contribute if it's in the road map.

**Comment by rdingwall** [comment]
hey @pimbrouwers I'm not really maintaining this anymore - I'd be happy to accept a pull request or add you as a contributor if you're volunteering 😉

**Comment by pimbrouwers** [comment]
I would love that. This repo has been so beneficial for me that I would be happy to give back in any way that I can. Perhaps a fork and subsequent pull request would be cleanest?

**Comment by rdingwall** [comment]
Sure! That would be great! What's the standard for supporting .Net core and traditional . Net in the same nuget package? Are they separate DLLs in different framework folders? Are they separate vs projects or can you target the same project for multiple outputs?

**Comment by pimbrouwers** [comment]
You can use compiler hints if a shared repo is desired. However, in my experience it's probably best to have separate bases for each. For example, the main repo supports up until the latest version of .net framework. "Protobuf-netcore-data" will support core and its future iterations. Thoughts?

**Comment by rdingwall** [comment]
That sounds great - so 2 separate nuget packages? Would you fork this one and rename it and publish it yourself? (that would be ideal I think - from time constraints I don't have a lot of time to work on this at the moment 😢 )

**Comment by pimbrouwers** [comment]
Agreed, I think it'll be easiest to work with it side by side and create a new project and nuget package.  If I encounter anything that might need clarification, I'll reach out.

**Comment by marfenij** [comment]
if it still in time, I was added https://github.com/rdingwall/protobuf-net-data/pull/36 to support .Net Core in one package, but @rdingwall don't answer yet (

**Comment by dotarj** [comment]
Support for .NET Standard 2.0 is added in [version 2.1.0](https://github.com/dotarj/protobuf-net-data/releases/tag/2.1.0).
