### ISSUE TITLE
Possible bug in RecordReader

### ISSUE THREAD

**Issue by rimuln** [dotarj/protobuf-net-data#58]
Hi, we have upgraded this lib in our project from 2.1.1 to 3.0.0

We have pgsql database that could be exported to XmlDataset and then this is serialized to file with protobuf 2.4 and this project.
XmlDataset contains multiple DataTables

Serialization works fine and for the concrete DataTable is saved all 15 columns. This DataTable isn't first in processing. Before it is table with 10 columns.

During next start of application is loaded serialized file and it is deserialized. Here we come to 
IndexBoundOfException in ProtoDataReader#GetValues(object[] values) at line 205
reason is that values has size 15. this is correct because table should have 15 columns 
=> valuesCount has value 15 too.
BUT context.Buffers has size only 10.

So I tried debug and tried to find where is problem.
I didn't fully get the call tree.
What I found is code in RecordReader#ReadRecord(ProtoReaderContext context)
in this method is context.Buffers created/initialized and if isn't null then it is only cleared.

First DataTable that is deserialized have 10 columns. Is it possible when next DataTable is deserialized that context.Buffers isn't reset to null so then buffers are only cleared and this lead to this error?

During ReadRecordValues it comes for columns 11-15 into the if at line 52 and values are skipped.

This is way how file is loaded and created:

```
public static XMLDataSet LoadXML() {
            database = new XMLDataSet();
            using (var reader = DataSerializer.Deserialize(new GZipStream(new FileStream(soubor, FileMode.Open), CompressionMode.Decompress))) {
                var tables = new List<DataTable>();
                foreach (DataTable table in database.Tables) {
                    tables.Add(table);
                }
                database.Load(reader, LoadOption.OverwriteChanges, tables.ToArray());
            }
            return database;
        }

       public static void SaveXML(XMLDataSet database) {
            using (GZipStream gzip = new GZipStream(new FileStream(soubor, FileMode.Create), CompressionMode.Compress)) {
                database.SchemaSerializationMode = SchemaSerializationMode.ExcludeSchema;
                database.RemotingFormat = SerializationFormat.Binary;
                DataSerializer.Serialize(gzip, database);
                gzip.Flush();
            }
        }
```

**Comment by rimuln** [comment]
This fixed the problem for me:
added is the OR part in condition
RecordReader#ReadRecord(ProtoReaderContext context)

```
            if (context.Buffers == null || (context.Buffers != null && context.Buffers.Length < context.Columns.Count))
            {
                context.Buffers = new ProtoDataBuffer[context.Columns.Count];

                ProtoDataBuffer.Initialize(context.Buffers);
            }
            else
            {
                ProtoDataBuffer.Clear(context.Buffers);
            }
```

**Comment by Franki1986** [comment]
Same here, after updating to version 3 the deserialization of a dataset does not work any more..

**Comment by DigitalDan1** [comment]
We've seen this same issue; after upgrading we get "IndexOutOfRangeException : Index was outside the bounds of the array."

Looking the code in RecordReader, it sets the buffer size (number of columns) for the first table in the reader so if any later tables have more columns the exception is thrown when trying to access the buffer.  This happens when calling `GetValue` and `IsDBNull` for example.

I've written a test and a (slightly simpler) fix.  I'll raise a PR for these.
